baseurl: ""
destination: ./_site
lsi:         false
port: 4000
markdown: kramdown
encoding: utf-8
permalink: /:year/:month/:title/
pygments: true
paginate: 5
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex