baseurl: ""
destination: ./_site
lsi:         false
port: 4000
markdown: kramdown
encoding: utf-8
permalink: /:year/:month/:title/
pygments: false
paginate: 1
name: InQlik blog
description: Blog about various aspects of QlikView development process 
url: http://inqlik.github.io/
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex